apiVersion: apps/v1
kind: Deployment
metadata:
  name: sito-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sito-api
  template:
    metadata:
      labels:
        app: sito-api
    spec:
      containers:
      - name: api
        image: sito:latest
        imagePullPolicy: Never
        env:
        - name: ROLE
          value: "api"
        - name: REDIS_HOST
          value: "redis"
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: data
          mountPath: /data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: sito-data
---
apiVersion: v1
kind: Service
metadata:
  name: sito-api
spec:
  type: LoadBalancer
  selector:
    app: sito-api
  ports:
  - port: 80
    targetPort: 8080
